//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAStudentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        public long HourID { get; set; }
        public System.DateTime HourDate { get; set; }
        public decimal HourAmount { get; set; }
        public string HourNotes { get; set; }
        public string Username { get; set; }
    
        public virtual User User { get; set; }
    }
}
