//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAStudentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long NoteID { get; set; }
        public string Note1 { get; set; }
        public long RecordID { get; set; }
        public string Username { get; set; }
    
        public virtual Record Record { get; set; }
        public virtual User User { get; set; }
    }
}
