//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAStudentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessingError
    {
        public long ErrorID { get; set; }
        public Nullable<long> ProcID { get; set; }
        public byte ErrorTypeID { get; set; }
        public Nullable<byte> ErrorComID { get; set; }
        public System.DateTime DateFound { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public string Note { get; set; }
    
        public virtual Processing Processing { get; set; }
        public virtual ErrorComplete ErrorComplete { get; set; }
        public virtual ErrorType ErrorType { get; set; }
    }
}
