//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAStudentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Queue()
        {
            this.Processing = new HashSet<Processing>();
            this.QueuePriority = new HashSet<QueuePriority>();
            this.Queue1 = new HashSet<Queue>();
            this.User = new HashSet<User>();
            this.Queue11 = new HashSet<Queue>();
            this.WeightedFile = new HashSet<WeightedFile>();
        }
    
        public short QueueID { get; set; }
        public string QueueDescription { get; set; }
        public Nullable<short> QueueNextQueue { get; set; }
        public Nullable<short> GroupID { get; set; }
        public short QueueOrderID { get; set; }
        public int FilesInQueue { get; set; }
        public bool AuditQueue { get; set; }
        public Nullable<short> AuditQueueAssigned { get; set; }
        public decimal AuditPercent { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Processing> Processing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueuePriority> QueuePriority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue> Queue1 { get; set; }
        public virtual Queue Queue2 { get; set; }
        public virtual QueueOrder QueueOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue> Queue11 { get; set; }
        public virtual Queue Queue21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightedFile> WeightedFile { get; set; }
    }
}
