//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFAStudentTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        public int TimeEntryId { get; set; }
        public System.DateTime TimeEntryStart { get; set; }
        public Nullable<System.DateTime> TimeEntryEnd { get; set; }
        public string TimeEntryDescription { get; set; }
        public int TimeCategoryId { get; set; }
        public string Username { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual TimeCategory TimeCategory { get; set; }
        public virtual User User { get; set; }
    }
}
